apiVersion: v1
kind: Service
metadata:
	name: gateway.service
	label:
		name: gateway.service
		app: microservice
spec:
	type: LoadBalancer
	ports:
		- port: 80
		  targetPort: 80
		  nodePort: 300010
	selector:
		app: gateway
		type: microservice