apiVersion: apps/v1
kind: Deployment
metadata:
	name: microservice.seguridad.deploy
	labels:
		name: microservice.seguridad.deploy
		app: microservice
spec:
	replicas: 2
	selector: 
		matchlabels:
			app: microservice.seguridad
			type: microservice
	template:
		metadata:
			name: microservice.seguridad.pod
			labels:
				app: microservice.seguridad
				type: microservice
		spec:
			containers:
			- name: microservice.seguridad.app
			  image: codernuby/serviciosapiseguridad:latest
			  ports:
				- containerPort: 88
			  env:
				- name: ConnectionStrings__ConexionDB
				  value: Server=mssql.service;Database=Seguridad;User=sa;Password=$VaxiDrez2025